<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$config = array(
	'cfg_site' => array(
			'standard_mall'	=>	'kor',
			'kor'	=> array(
				'title'	=> 'Blooming Terra Inc.',
				'nameKor'	=> 'Blooming Terra Inc.',
				'nameEng'	=> 'BloomingTerra',
				'adminEmail'	=> 'info@askim.kr',
				'compName'	=> 'Blooming Terra Inc.',
				'item'	=> ' ',
				'service'	=> ' ',
				'zipcode'	=> ' ',
				'address'	=> '1001 Wilshire Boulevard #1349 Los Angeles, CA 90017',
				'ceoName'	=> ' ',
				'compSerial'	=> ' ',
				'retailBusiness'	=> ' ',
				'adminName'	=> ' ',
				'compPhone'	=> ' ',
				'compFax'	=> '  ',
				'smsRecall'	=> ' ',
				'customerHour'	=> ' ',
			),
			'eng'	=> array(
				'title'	=> 'Askim Company Inc.',
				'nameKor'	=> 'Askim Company Inc.',
				'nameEng'	=> 'BloomingTerra',
				'adminEmail'	=> 'info@bloomingterra.kr',
				'compName'	=> 'Askim Company Inc.',
				'item'	=> ' ',
				'service'	=> ' ',
				'zipcode'	=> ' ',
				'address'	=> '#502, Seongjin Cowon Tower, 31, Seoungsui-ro 24-gil, Seongdong-gu, Seoul, Korea, 04798',
				'ceoName'	=> ' ',
				'compSerial'	=> '336-87-02990',
				'retailBusiness'	=> ' ',
				'adminName'	=> ' ',
				'compPhone'	=> ' 02-554-8110',
				'compFax'	=> ' ',
				'smsRecall'	=> ' ',
				'customerHour'	=> ' ',
			),
			'chn'	=> array(
				'title'	=> '设计艺术1 ',
				'nameKor'	=> '智能传感器 ',
				'nameEng'	=> 'Gabia ',
				'adminEmail'	=> 'help@designart.co.kr',
				'compName'	=> 'D-设计艺术',
				'item'	=> 'IT ',
				'service'	=> '디자인 ',
				'zipcode'	=> '000000 ',
				'address'	=> '경기도 성남시 분당구 대왕판교로 660 4층 ',
				'ceoName'	=> '김홍국 ',
				'compSerial'	=> '214-86-3923 ',
				'retailBusiness'	=> '12345678 ',
				'adminName'	=> '홍길동 ',
				'compPhone'	=> '02-1544-3270 ',
				'compFax'	=> '02-1544-3270 ',
				'smsRecall'	=> '07000000000 ',
				'customerHour'	=> '평일 :AM 03:00 ~ PM 06:00<br>점심시간 :12:00 ~ 13:00 / 토,일,공휴일 휴무 ',
			),
			'jpn'	=> array(
				'title'	=> 'DesignArtJp1 ',
				'nameKor'	=> 'スマートセンサー ',
				'nameEng'	=> 'Gabia ',
				'adminEmail'	=> 'help@designart.co.kr',
				'compName'	=> 'D-デザインアーツ',
				'item'	=> 'IT ',
				'service'	=> '디자인 ',
				'zipcode'	=> '000000 ',
				'address'	=> '경기도 성남시 분당구 대왕판교로 660 4층 ',
				'ceoName'	=> '김홍국 ',
				'compSerial'	=> '214-86-3923 ',
				'retailBusiness'	=> '12345678 ',
				'adminName'	=> '홍길동 ',
				'compPhone'	=> '02-1544-3270 ',
				'compFax'	=> '02-1544-3270 ',
				'smsRecall'	=> '07000000000 ',
				'customerHour'	=> '평일 :AM 09:00 ~ PM 06:00<br>점심시간 :12:00 ~ 13:00 / 토,일,공휴일 휴무 ',
			),
		'seo' => array(
			'author'	=> 'dd작성자',
			'description'	=> '설명',
			'keywords'	=> '키워드 ',
			'snsTitle'	=> '대표제목',
			'snsDescription'	=> '대표설명 ',
			'favicon'	=> 'garden_logo_R0c_icon.ico',
			'snsImage'	=> 'restmb_idxmake.jpg',
			'sitemap'	=> 'sitemap.xml',
		),
	),
);
